# Generated by Django 3.2.23 on 2023-11-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('ExpiryDate', models.DateField()),
                ('category', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('chemicalcomposition', models.CharField(max_length=200)),
            ],
        ),
    ]
