# Generated by Django 3.2.23 on 2023-11-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PharmalyticsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication',
            old_name='ExpiryDate',
            new_name='expirydate',
        ),
        migrations.AlterField(
            model_name='medication',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
