# Generated by Django 4.2.5 on 2023-11-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PharmalyticsApp', '0003_alter_medication_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('dateofbirth', models.DateField()),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=10, null=True)),
                ('phonenumber', models.IntegerField()),
                ('insurancecompany', models.CharField(max_length=50, null=True)),
                ('permanentmedication', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='medication',
            name='dosage',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medication',
            name='sideeffects',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='substitute',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='category',
            field=models.CharField(choices=[('Blood Pressure', 'Blood'), ('Diabetes', 'Diabetes'), ('Gastro', 'Gastro'), ('Pregnancy', 'Pregnancy'), ('Infants', 'Infants'), ('Pain Killer', 'Pain'), ('Other', 'Other')], default='Blood Pressure', max_length=50),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='medication',
            name='provider',
            field=models.CharField(max_length=100),
        ),
    ]
