# Generated by Django 4.2.5 on 2023-11-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PharmalyticsApp', '0004_customers_medication_dosage_medication_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=100)),
                ('provideremail', models.EmailField(max_length=254)),
                ('medname', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
