# Generated by Django 4.2.5 on 2023-11-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PharmalyticsApp', '0005_medicationorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='substitute',
        ),
        migrations.AlterField(
            model_name='medication',
            name='chemicalcomposition',
            field=models.JSONField(),
        ),
    ]
