# Generated by Django 4.2.5 on 2023-11-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PharmalyticsApp', '0007_alter_medication_chemicalcomposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='substitute',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='chemicalcomposition',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
