# Generated by Django 3.2.24 on 2024-03-03 09:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PharmalyticsApp', '0008_medication_substitute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='barcode',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='medicationorder',
            name='orderdate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='customers',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other'), ('Prefer not to specify', 'Nospecify')], max_length=25, null=True),
        ),
        migrations.CreateModel(
            name='SalesTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.PositiveIntegerField()),
                ('price_per_unit', models.IntegerField()),
                ('payment_method', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PharmalyticsApp.medication')),
            ],
        ),
    ]
