# Generated by Django 5.0.3 on 2024-03-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PharmalyticsApp', '0010_salestransaction_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestransaction',
            name='customeremail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
